version: "3.1"

services:
  es:
    image: elasticsearch:7.17.7
    container_name: elasticsearch_app
    restart: always
    environment:
      - node.name=single-node
      - discovery.type=single-node
      - cluster.name=${CLUSTER_NAME}
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - pjt-bridge
    volumes:
      - elasticsearch-data:${DIR_MOUNTED_ELASTICSEARCH}
    command: sh -c "
        if [ ! -d ${DIR_MOUNTED_ELASTICSEARCH} ]; then
          mkdir -p ${DIR_MOUNTED_ELASTICSEARCH} && chmod 777 ${DIR_MOUNTED_ELASTICSEARCH};
        fi;
        chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data;
        su elasticsearch -c /usr/share/elasticsearch/bin/elasticsearch"

  mysql:
    image: mysql:8-oracle
    container_name: mysql_app
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    networks:
      - pjt-bridge
    volumes:
      - mysql-data:${DIR_MOUNTED_MYSQL}
    command: sh -c "
        if [ ! -d ${DIR_MOUNTED_MYSQL} ]; then
          mkdir -p ${DIR_MOUNTED_MYSQL} && chmod 777 ${DIR_MOUNTED_MYSQL};
        fi;
        chown -R mysql:mysql /var/lib/mysql;
        exec mysqld"

  spring:
    container_name: spring_app
    image: iksadnorth/spring_app:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - es
      - mysql
    networks:
      - pjt-bridge
  
  nginx_vue:
    container_name: nginx_vue
    image: iksadnorth/vue_app:latest
    restart: always
    ports:
      - 80:80
    networks:
      - pjt-bridge

networks:
  pjt-bridge:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR_MOUNTED_ELASTICSEARCH}
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DIR_MOUNTED_MYSQL}
